services:
  # PostgreSQL Database for CMS Service
  postgres-cms:
    extends:
      file: compose.base.yaml
      service: postgres-cms

  # RabbitMQ for CMS Service
  rabbitmq-cms:
    extends:
      file: compose.base.yaml
      service: rabbitmq-cms

  # MailHog for local email testing
  mailhog:
    extends:
      file: compose.base.yaml
      service: mailhog

  # DbGate - Database Administration Tool
  dbgate:
    extends:
      file: compose.base.yaml
      service: dbgate

  # SonarQube for code quality analysis
  sonar:
    extends:
      file: compose.base.yaml
      service: sonar

  # Prometheus for metrics collection
  prometheus:
    extends:
      file: compose.base.yaml
      service: prometheus

  # Grafana for metrics visualization
  grafana:
    extends:
      file: compose.base.yaml
      service: grafana

networks:
  cms-service-network:
    name: foundation-cms-network-dev
    external: false

volumes:
  postgres_cms_data:
    name: iqkv_cms_postgres_data_dev
  rabbitmq_cms_data:
    name: iqkv_cms_rabbitmq_data_dev
  dbgate_cms_data:
    name: iqkv_cms_dbgate_data_dev
  cms_logs:
    name: iqkv_cms_logs_dev
  cms_tmp:
    name: iqkv_cms_tmp_dev
