services:
  # PostgreSQL Database for Cms
  postgres-cms:
    extends:
      file: compose.base.yaml
      service: postgres-cms

  # RabbitMQ for Cms
  rabbitmq-cms:
    extends:
      file: compose.base.yaml
      service: rabbitmq-cms

  # MailHog for local email testing
  mailhog:
    extends:
      file: compose.base.yaml
      service: mailhog

  # DbGate - Database Administration Tool
  dbgate:
    extends:
      file: compose.base.yaml
      service: dbgate

  # Cms - Full platform run including build phase
  cms:
    extends:
      file: compose.base.yaml
      service: cms

networks:
  cms-network:
    name: foundation-cms-network-dev
    external: false

volumes:
  postgres_cms_data:
    name: iqkv_cms_postgres_data_dev
  rabbitmq_cms_data:
    name: iqkv_cms_rabbitmq_data_dev
  dbgate_cms_data:
    name: iqkv_cms_dbgate_data_dev
  cms_logs:
    name: cms_logs_dev
  cms_tmp:
    name: cms_tmp_dev
